/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IProblem, IProblemInterface } from "../IProblem";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "contestant",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "version",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "point",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "enum Verdict[]",
        name: "verdicts",
        type: "uint8[]",
      },
    ],
    name: "RunSolution",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "contestant",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "solution",
        type: "address",
      },
    ],
    name: "UpdateSolution",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "contestant",
        type: "address",
      },
    ],
    name: "getContestantInfo",
    outputs: [
      {
        internalType: "address",
        name: "solution",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "point",
        type: "uint32",
      },
      {
        internalType: "bool",
        name: "isPointUpToDate",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "contestant",
        type: "address",
      },
    ],
    name: "runSolution",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "solution",
        type: "address",
      },
    ],
    name: "updateAndRunSolution",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "solution",
        type: "address",
      },
    ],
    name: "updateSolution",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IProblem__factory {
  static readonly abi = _abi;
  static createInterface(): IProblemInterface {
    return new utils.Interface(_abi) as IProblemInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IProblem {
    return new Contract(address, _abi, signerOrProvider) as IProblem;
  }
}
