/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface IGateInterface extends utils.Interface {
  contractName: "IGate";
  functions: {
    "deploy(bytes)": FunctionFragment;
    "deployAndRun(bytes,bytes)": FunctionFragment;
    "solutionId(address)": FunctionFragment;
    "user()": FunctionFragment;
    "username()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "deploy", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "deployAndRun",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "solutionId", values: [string]): string;
  encodeFunctionData(functionFragment: "user", values?: undefined): string;
  encodeFunctionData(functionFragment: "username", values?: undefined): string;

  decodeFunctionResult(functionFragment: "deploy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployAndRun",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "solutionId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "user", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "username", data: BytesLike): Result;

  events: {
    "Deployment(uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Deployment"): EventFragment;
}

export type DeploymentEvent = TypedEvent<
  [BigNumber, string],
  { id: BigNumber; solution: string }
>;

export type DeploymentEventFilter = TypedEventFilter<DeploymentEvent>;

export interface IGate extends BaseContract {
  contractName: "IGate";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IGateInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deploy(
      bytecode: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deployAndRun(
      bytecode: BytesLike,
      input: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    solutionId(
      solution: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { id: BigNumber }>;

    user(overrides?: CallOverrides): Promise<[string]>;

    username(
      overrides?: CallOverrides
    ): Promise<[string] & { username: string }>;
  };

  deploy(
    bytecode: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deployAndRun(
    bytecode: BytesLike,
    input: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  solutionId(solution: string, overrides?: CallOverrides): Promise<BigNumber>;

  user(overrides?: CallOverrides): Promise<string>;

  username(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    deploy(bytecode: BytesLike, overrides?: CallOverrides): Promise<string>;

    deployAndRun(
      bytecode: BytesLike,
      input: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    solutionId(solution: string, overrides?: CallOverrides): Promise<BigNumber>;

    user(overrides?: CallOverrides): Promise<string>;

    username(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "Deployment(uint256,address)"(
      id?: null,
      solution?: null
    ): DeploymentEventFilter;
    Deployment(id?: null, solution?: null): DeploymentEventFilter;
  };

  estimateGas: {
    deploy(
      bytecode: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deployAndRun(
      bytecode: BytesLike,
      input: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    solutionId(solution: string, overrides?: CallOverrides): Promise<BigNumber>;

    user(overrides?: CallOverrides): Promise<BigNumber>;

    username(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    deploy(
      bytecode: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deployAndRun(
      bytecode: BytesLike,
      input: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    solutionId(
      solution: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    user(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    username(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
