name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dev dependencies
        run: npm install

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Set up rust cache
        uses: Swatinem/rust-cache@v1

      - name: Install Forge
        run: |
          cargo install --git https://github.com/gakonst/foundry --bin forge --locked

      - name: Run lint check
        run: npm run lint:check

      - name: Run tests
        run: forge test
